### ISSUE TITLE
Entity as Object, not just string | Uint8Array ?

### ISSUE THREAD

**Issue by mike-hogan** [http4t/http4t#36]
This might be related to https://github.com/http4t/http4t/issues/9

Just started using this today, but seems entities boiled down to string or byte array (or promised versions of the same).

My current need is to get a response from a service provider's API, and run that response through a couple of transformers to reshape the response.  Each of these transformers is therefore converting the data from a string to an object and back again.

So I'm prompted to ask whether there is scope to have the entity be a plain object, with marshalling to and from strings just at the edges?

Happy to rewrite this question if none of it makes sense :)

**Comment by savagematt** [comment]
We're still figuring out how we want to do this.

The whole premise of http4t is that our APIs are true to the HTTP wire format, in order to have the smallest possible implementation footprint and the least ambiguity. We want it to be really obvious what's happening, all the time.

We recognise the problem though. We're just scratching our heads over how (and whether) there's a way to cleanly deal with json bodies.

Suggestions welcome.

**Comment by danielbodart** [comment]
Hey Mike, if you look at the core contract you will see the http4t supports known or unknown length bodies (as well as sync or async):

```
/**
 * SyncBody can be fixed or unknown length.
 */
export type SyncBody = Data | Iterable<Data>;
```

So if you want to return an object you obviously don't know it's length so you just make your object return an iterable. I've used this on http4js as well and just created a simple class called JsonBody or ObjectBody(with a renderer function) that has a value: T and will serialise to a single string if you iterate.

Whats really cool with this is if the object does get big you can then actually streams chunks of JSON and never hold the whole thing in memory.

This allows one to add support for renderers like UI had but again without the core library knowing about it!

**Comment by savagematt** [comment]
I’d _just_ got to JsonBody :) ObjectBody even cooler.

Then jsonBody(request) that doesn’t deserialise?  I’m still learning what’s acceptable javascript- is instanceof JsonBody a sensible way to check?

**Comment by savagematt** [comment]
see https://github.com/http4t/http4t/blob/master/http4t-core/src/json.ts
